version: '3'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'bitnami/minio:2024.4.6'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - app-tier
